name: Build
on:
  workflow_call:
    inputs:
      upload-artifact:
        type: boolean
        default: true
      tag-name:
        type: string
        default: "draft"
      channel:
        type: string
        default: "dev"

env:
  IS_GITHUB_ACTIONS: 1
  CHANNEL: "${{ inputs.channel }}"
  NDK_VERSION: r28c
  UPLOAD_ARTIFACT: "${{ inputs.upload-artifact }}"
  TAG_NAME: "${{ inputs.tag-name }}"
  TARGET_NAME_gz: "NexVPN-Linux-x64-AppImage.tar"
  TARGET_NAME_AppImage: "NexVPN-Linux-x64-AppImage"
  TARGET_NAME_deb: "NexVPN-Debian-x64"
  TARGET_NAME_apk: "NexVPN-Android"
  TARGET_NAME_aab: "NexVPN-Android"
  TARGET_NAME_exe: "NexVPN-Windows-Setup-x64"
  TARGET_NAME_msix: "NexVPN-Windows-x64"
  TARGET_NAME_zip: "NexVPN-Windows-Portable-x64"
  TARGET_NAME_dmg: "NexVPN-MacOS"
  TARGET_NAME_pkg: "NexVPN-MacOS-Installer"
  TARGET_NAME_ipa: "NexVPN-iOS"

jobs:
  build:
    permissions: write-all
    continue-on-error: true

    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: android-apk
            os: ubuntu-latest
            targets: apk

          - platform: android-aab
            os: ubuntu-latest
            targets: aab

          - platform: windows
            os: windows-latest
            aarch: amd64
            targets: exe,msix,zip

          - platform: linux
            os: ubuntu-22.04
            aarch: amd64
            targets: deb,gz,AppImage

          - platform: macos
            os: macos-15
            aarch: universal
            targets: dmg,pkg

    runs-on: ${{ matrix.os }}
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Import Apple Codesign Certificates
        if: ${{ inputs.upload-artifact && startsWith(matrix.os,'macos') }}
        continue-on-error: true
        uses: apple-actions/import-codesign-certs@v3
        with:
            p12-file-base64: "${{ secrets.APPLE_CERTIFICATE_P12 }}"
            p12-password: "${{ secrets.APPLE_CERTIFICATE_P12_PASSWORD }}"

      - name: Import Apple Mobile Provisioning Profile
        if: ${{ inputs.upload-artifact && startsWith(matrix.os,'macos') }}
        run: |
           mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
           echo "${{secrets.APPLE_MOBILE_PROVISIONING_PROFILES_TARGZ_BASE64}}"|base64 --decode | tar xz -C ~/Library/MobileDevice/Provisioning\ Profiles
           security unlock-keychain -p "" signing_temp.keychain || true
           security find-identity -v -p codesigning || true

      - name: Setup Flutter
        uses: flutter-actions/setup-flutter@v4
        with:
          channel: stable
          version: 3.38.5

      - name: Clean up disk space
        if: startsWith(matrix.platform,'android')
        run: |
          sudo rm -rf /usr/share/dotnet || true
          sudo rm -rf /opt/ghc || true
          sudo rm -rf /opt/hostedtoolcache/CodeQL || true
          rm -rf ~/.gradle/caches || true
          sudo apt-get autoremove -y
          sudo apt-get clean

      - name: Setup Java
        if: startsWith(matrix.platform,'android')
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        if: startsWith(matrix.platform,'android')

      - name: Cache Gradle
        uses: actions/cache@v4
        if: startsWith(matrix.platform,'android')
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}-

      - name: Setup dependencies
        run: |
          make ${{ matrix.platform }}-install-deps
          echo "$HOME/.pub-cache/bin" >> $GITHUB_PATH

      - name: Setup Android Signing Properties
        if: ${{ inputs.upload-artifact && startsWith(matrix.platform,'android') }}
        run: |
          echo "${{ secrets.ANDROID_SIGNING_KEY }}" | base64 --decode > android/key.jks
          echo "storeFile=$(pwd)/android/key.jks" > android/key.properties
          echo "storePassword=${{ secrets.ANDROID_SIGNING_STORE_PASSWORD }}" >> android/key.properties
          echo "keyPassword=${{ secrets.ANDROID_SIGNING_KEY_PASSWORD }}" >> android/key.properties
          echo "keyAlias=${{ secrets.ANDROID_SIGNING_KEY_ALIAS }}" >> android/key.properties

      - name: Setup Windows Signing Properties
        if: ${{ inputs.upload-artifact && startsWith(matrix.platform,'windows') }}
        run: |
            [IO.File]::WriteAllBytes("windows\sign.pfx", [Convert]::FromBase64String("${{ secrets.WINDOWS_SIGNING_KEY }}"))
            (Get-Content "windows\packaging\msix\make_config.yaml") -replace '^certificate_password:.*$', 'certificate_password: ${{ secrets.WINDOWS_SIGNING_PASSWORD }}' | Set-Content "windows\packaging\msix\make_config.yaml"

      - name: Prepare for ${{ matrix.platform }}
        run: make ${{ matrix.platform }}-prepare

      - name: Build ${{ matrix.platform }}
        env:
          SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
        run: make ${{ matrix.platform }}-release

      - name: Copy to out Windows
        if: matrix.platform == 'windows'
        shell: pwsh
        run: |
          New-Item -ItemType Directory -Path "out" -Force | Out-Null
          $targets = "${{ matrix.targets }}".Split(',')
          foreach ($ext in $targets) {
            $ext = $ext.Trim()
            $key = "TARGET_NAME_$ext"
            $targetName = (Get-Item "env:$key").Value
            $files = Get-ChildItem -Path dist -Recurse -Filter "*.$ext" -ErrorAction SilentlyContinue
            foreach ($file in $files) {
                $destination = Join-Path -Path "out" -ChildPath "$targetName.$ext"
                Move-Item -Path $file.FullName -Destination $destination -Force
            }
          }

      - name: Copy to out Android APK
        if: matrix.platform == 'android-apk'
        run: |
          mkdir -p out
          cp ./build/app/outputs/flutter-apk/*arm64-v8a*.apk out/${TARGET_NAME_apk}-arm64.apk || true
          cp ./build/app/outputs/flutter-apk/*armeabi-v7a*.apk out/${TARGET_NAME_apk}-arm7.apk || true
          cp ./build/app/outputs/flutter-apk/*x86_64*.apk out/${TARGET_NAME_apk}-x86_64.apk || true
          cp ./build/app/outputs/flutter-apk/app-release.apk out/${TARGET_NAME_apk}-universal.apk || true
          ls out/

      - name: Copy to out Android AAB
        if: matrix.platform == 'android-aab'
        run: |
          mkdir -p out
          cp ./build/app/outputs/bundle/release/app-release.aab out/nexvpn-android-market.aab || true

      - name: Copy to out unix
        if: startsWith(matrix.platform,'linux') || matrix.platform == 'macos'
        run: |
          mkdir -p out tmp_out
          for EXT in $(echo ${{ matrix.targets }} | tr ',' '\n'); do
            KEY=TARGET_NAME_${EXT}
            FILENAME=${!KEY}
            find dist -name "*.$EXT" -exec mv {} tmp_out/${FILENAME}.$EXT \; || true
            [[ "$EXT" != "gz" ]] && chmod +x tmp_out/${FILENAME}.$EXT 2>/dev/null || true
            mv tmp_out/${FILENAME}.$EXT out/ 2>/dev/null || true
          done

      - name: Upload Artifact
        if: env.UPLOAD_ARTIFACT == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: ${{matrix.platform}}
          path: ./out
          retention-days: 1

      - name: Clean up keychain
        if: ${{ always() && startsWith(matrix.os,'macos') }}
        run: |
          security delete-keychain $RUNNER_TEMP/app-signing.keychain-db 2>/dev/null || true
          rm ~/Library/MobileDevice/Provisioning\ Profiles/*.mobileprovision 2>/dev/null || true

  update-draft:
    permissions: write-all
    if: ${{ inputs.upload-artifact }}
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          merge-multiple: true
          pattern: "*"
          path: ./out/

      - name: List files
        run: ls -R ./out || echo "No files"

      - name: Create or Update Draft Release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: ./out/*
          name: 'NexVPN draft'
          tag_name: 'draft'
          prerelease: true

  upload-release:
    permissions: write-all
    if: ${{ inputs.upload-artifact && inputs.tag-name != 'draft' }}
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          merge-multiple: true
          pattern: "*"
          path: ./out/

      - name: Upload Release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          prerelease: true
          tag_name: ${{ inputs.tag-name }}
          files: ./out/*
